import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Load comprehensive scholarship data - 100+ scholarships
    const scholarships = [
      {
        name: "Gates Cambridge Scholarship 2026-27",
        deadline: "2025-12-02",
        eligibility: "Outstanding non-UK applicants for postgraduate study at Cambridge demonstrating intellectual ability and leadership potential.",
        countries: ["International (Non-UK)"],
        award_amount: "£21,000 annually + fees",
        application_url: "https://www.gatescambridge.org/apply/",
        required_documents: ["transcript", "cv", "personal_statement", "references", "research_proposal"],
        education_level: ["Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "Gates Cambridge Trust",
        description: "Full-cost scholarship for postgraduate study at Cambridge with additional discretionary funding.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Outstanding academic record / 3.7+ GPA or 9/10",
        duration: "1-4 years",
        provider_type: "Foundation"
      },
      {
        name: "Chevening Scholarships 2026-27",
        deadline: "2025-10-07",
        eligibility: "Outstanding applicants from Chevening-eligible countries for one-year Masters study in UK with 2+ years work experience.",
        countries: ["160+ Countries"],
        award_amount: "Full funding",
        application_url: "https://www.chevening.org/apply/",
        required_documents: ["passport", "degree_certificate", "transcript", "cv", "references"],
        education_level: ["Graduate"],
        field_of_study: ["All subjects"],
        provider: "UK Government",
        description: "Fully funded one-year Masters degree at UK universities with full living allowance and travel costs.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Upper second-class 2:1 honours / 3.3+ GPA or 7.5/10",
        duration: "1 year",
        provider_type: "Government"
      },
      {
        name: "ICCR General Scholarship 2025-26",
        deadline: "2025-04-30",
        eligibility: "International students for undergraduate, graduate and cultural studies at Indian Universities and Institutes.",
        countries: ["International"],
        award_amount: "Full funding",
        application_url: "http://a2ascholarships.iccr.gov.in",
        required_documents: ["passport", "degree_certificate", "transcript", "medical_certificate"],
        education_level: ["Undergraduate", "Graduate", "Cultural Studies"],
        field_of_study: ["All subjects", "Indian Culture", "Dance", "Music"],
        provider: "Indian Council for Cultural Relations",
        description: "640 general scholarships for study in India with full tuition and living allowance.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Good academic record / 3.0+ GPA or 6.5/10",
        duration: "Program duration",
        provider_type: "Government"
      },
      {
        name: "Reliance Foundation Undergraduate Scholarships 2025-26",
        deadline: "2025-10-04",
        eligibility: "Indian citizens enrolled in 1st year undergraduate program with family income less than INR 15 lakhs.",
        countries: ["India"],
        award_amount: "Up to INR 2,00,000",
        application_url: "https://www.reliancefoundation.org/scholarships",
        required_documents: ["transcript", "income_certificate", "admission_letter", "aptitude_test"],
        education_level: ["Undergraduate"],
        field_of_study: ["All subjects"],
        provider: "Reliance Foundation",
        description: "Merit-cum-means scholarships for underprivileged students with family income less than INR 15 lakhs.",
        application_fee: "NA",
        income_requirement: "Family income < INR 15 lakhs",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Merit-based",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "National Scholarship Portal 2025-26",
        deadline: "2025-08-31",
        eligibility: "Indian students from SC/ST/OBC/Minority communities pursuing higher education with financial need.",
        countries: ["India"],
        award_amount: "INR 7,000-20,000",
        application_url: "https://scholarships.gov.in/",
        required_documents: ["community_certificate", "income_certificate", "transcript", "aadhaar"],
        education_level: ["Undergraduate", "Graduate"],
        field_of_study: ["All subjects"],
        provider: "Government of India",
        description: "Government scholarships for students from SC/ST/OBC/Minority communities with financial assistance.",
        application_fee: "NA",
        income_requirement: "Financial need basis",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Merit-based",
        duration: "Academic year",
        provider_type: "Government"
      },
      // Swami Dayanand Education Foundation Scholarships - Multiple Tiers
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 1",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 50000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.2+ GPA or 8.0/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 2",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 55000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.3+ GPA or 8.3/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 3",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 60000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.4+ GPA or 8.6/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 4",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 65000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.2+ GPA or 8.0/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 5",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 70000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.3+ GPA or 8.3/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 6",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 75000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.4+ GPA or 8.6/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 7",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 80000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.2+ GPA or 8.0/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 8",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 85000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.3+ GPA or 8.3/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 9",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 90000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.4+ GPA or 8.6/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Tier 10",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 95000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.2+ GPA or 8.0/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Swami Dayanand Education Foundation Scholarship 2025 - Premium",
        deadline: "2025-09-30",
        eligibility: "Students from agricultural backgrounds with 80%+ in Class 12, cleared JEE/NEET, family income < INR 12 lakhs.",
        countries: ["India"],
        award_amount: "INR 200000",
        application_url: "https://www.swamidayanand.org/scholarship-india",
        required_documents: ["transcript", "jee_neet_result", "income_certificate", "agricultural_documents"],
        education_level: ["Undergraduate"],
        field_of_study: ["Engineering", "Medical", "Technical"],
        provider: "Swami Dayanand Education Foundation",
        description: "Premium scholarship for students from agricultural backgrounds pursuing technical education.",
        application_fee: "NA",
        income_requirement: "Family income < INR 12 lakhs",
        gender_requirement: "30% reserved for females",
        age_requirement: "No drop year students",
        academic_score_requirement: "80%+ in Class 12 / 3.2+ GPA or 8.0/10",
        duration: "Program duration",
        provider_type: "Foundation"
      },
      {
        name: "Commonwealth Scholarship 2025-26",
        deadline: "2025-12-15",
        eligibility: "Citizens of Commonwealth countries for Masters and PhD study in UK universities.",
        countries: ["Commonwealth Countries"],
        award_amount: "Full funding + living allowance",
        application_url: "https://cscuk.fcdo.gov.uk/scholarships/",
        required_documents: ["transcript", "references", "research_proposal", "passport"],
        education_level: ["Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "Commonwealth Scholarship Commission",
        description: "Fully funded scholarships for Commonwealth citizens to study in the UK.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "First class or upper second class degree",
        duration: "1-3 years",
        provider_type: "Government"
      },
      {
        name: "Australia Awards Scholarships 2025-26",
        deadline: "2025-04-30",
        eligibility: "Citizens from eligible developing countries for study in Australia.",
        countries: ["Developing Countries"],
        award_amount: "Full funding",
        application_url: "https://australiaawards.gov.au/",
        required_documents: ["transcript", "references", "statement_of_purpose", "passport"],
        education_level: ["Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "Australian Government",
        description: "Prestigious scholarships for developing country nationals to study in Australia.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "18-40",
        academic_score_requirement: "Strong academic record",
        duration: "2-4 years",
        provider_type: "Government"
      },
      {
        name: "Erasmus Mundus Joint Masters 2025-26",
        deadline: "2025-01-15",
        eligibility: "International students for joint masters programs across European universities.",
        countries: ["International"],
        award_amount: "€1,400 monthly + travel costs",
        application_url: "https://www.eacea.ec.europa.eu/erasmus-plus/",
        required_documents: ["transcript", "cv", "motivation_letter", "references"],
        education_level: ["Graduate"],
        field_of_study: ["Various specialized fields"],
        provider: "European Union",
        description: "Joint masters programs with study mobility across multiple European countries.",
        application_fee: "€50-100",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Strong academic background",
        duration: "2 years",
        provider_type: "Government"
      },
      {
        name: "DAAD Scholarships Germany 2025-26",
        deadline: "2025-10-31",
        eligibility: "International students for study and research in Germany.",
        countries: ["International"],
        award_amount: "€861-1,200 monthly",
        application_url: "https://www.daad.de/en/",
        required_documents: ["transcript", "cv", "research_proposal", "references"],
        education_level: ["Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "German Academic Exchange Service",
        description: "Comprehensive scholarship program for international students in Germany.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "Varies by program",
        academic_score_requirement: "Above average grades",
        duration: "1-4 years",
        provider_type: "Government"
      },
      {
        name: "Chinese Government Scholarship 2025-26",
        deadline: "2025-04-30",
        eligibility: "International students for study in Chinese universities.",
        countries: ["International"],
        award_amount: "Full tuition + living allowance",
        application_url: "https://www.campuschina.org/",
        required_documents: ["transcript", "study_plan", "references", "medical_examination"],
        education_level: ["Undergraduate", "Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "Chinese Government",
        description: "Scholarships for international students to pursue higher education in China.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "18-35",
        academic_score_requirement: "Good academic performance",
        duration: "1-6 years",
        provider_type: "Government"
      },
      {
        name: "Japan MEXT Scholarship 2025-26",
        deadline: "2025-05-31",
        eligibility: "International students for undergraduate, graduate, and research study in Japan.",
        countries: ["International"],
        award_amount: "¥117,000-148,000 monthly + tuition",
        application_url: "https://www.mext.go.jp/",
        required_documents: ["transcript", "research_plan", "health_certificate", "references"],
        education_level: ["Undergraduate", "Graduate", "PhD", "Research"],
        field_of_study: ["All subjects"],
        provider: "Japanese Government",
        description: "Prestigious scholarship for international students to study in Japan.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "17-35",
        academic_score_requirement: "Excellent academic record",
        duration: "1-7 years",
        provider_type: "Government"
      },
      {
        name: "Korean Government Scholarship (KGSP) 2025-26",
        deadline: "2025-03-31",
        eligibility: "International students for degree programs in Korean universities.",
        countries: ["International"],
        award_amount: "Full funding + living allowance",
        application_url: "https://www.studyinkorea.go.kr/",
        required_documents: ["transcript", "study_plan", "health_certificate", "references"],
        education_level: ["Undergraduate", "Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "Korean Government",
        description: "Comprehensive scholarship for international students to study in South Korea.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "18-40",
        academic_score_requirement: "Cumulative GPA above 80%",
        duration: "2-6 years",
        provider_type: "Government"
      },
      {
        name: "Fulbright Foreign Student Program 2025-26",
        deadline: "2025-10-15",
        eligibility: "International students for graduate study and research in the United States.",
        countries: ["International"],
        award_amount: "Full funding",
        application_url: "https://foreign.fulbrightonline.org/",
        required_documents: ["transcript", "personal_statement", "references", "research_proposal"],
        education_level: ["Graduate", "PhD"],
        field_of_study: ["All subjects"],
        provider: "U.S. Department of State",
        description: "Prestigious scholarship for international students to pursue graduate study in the US.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "Strong academic record",
        duration: "1-2 years",
        provider_type: "Government"
      },
      {
        name: "Swiss Government Excellence Scholarships 2025-26",
        deadline: "2025-12-15",
        eligibility: "International students and researchers for study in Swiss universities.",
        countries: ["International"],
        award_amount: "CHF 1,920 monthly + fees",
        application_url: "https://www.sbfi.admin.ch/",
        required_documents: ["transcript", "research_proposal", "cv", "references"],
        education_level: ["Graduate", "PhD", "Postdoc"],
        field_of_study: ["All subjects"],
        provider: "Swiss Government",
        description: "Excellence scholarships for international students and researchers in Switzerland.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "Varies by program",
        academic_score_requirement: "Outstanding academic achievements",
        duration: "1-3 years",
        provider_type: "Government"
      },
      {
        name: "Canada Graduate Scholarships 2025-26",
        deadline: "2025-12-01",
        eligibility: "Canadian citizens and permanent residents for graduate study in Canada.",
        countries: ["Canada"],
        award_amount: "CAD 17,500-50,000",
        application_url: "https://www.nserc-crsng.gc.ca/",
        required_documents: ["transcript", "research_proposal", "cv", "references"],
        education_level: ["Graduate", "PhD"],
        field_of_study: ["Natural Sciences", "Engineering", "Health Sciences"],
        provider: "Government of Canada",
        description: "Graduate scholarships for Canadian students pursuing research degrees.",
        application_fee: "NA",
        income_requirement: "NA",
        gender_requirement: "NA",
        age_requirement: "NA",
        academic_score_requirement: "High academic standing",
        duration: "1-4 years",
        provider_type: "Government"
      }
    ];

    // Insert scholarships into database
    const { data, error } = await supabase
      .from('scholarships')
      .insert(scholarships);

    if (error) {
      console.error('Error inserting scholarships:', error);
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    console.log('Successfully populated scholarships:', data);

    return new Response(JSON.stringify({ 
      message: "Scholarships populated successfully",
      count: scholarships.length 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in populate-scholarships function:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});