// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lggqfbwvutyzkmdyswbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnZ3FmYnd2dXR5emttZHlzd2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjAyNzksImV4cCI6MjA3MzQzNjI3OX0.cimhh9AlOZ2t9rbkovBsdhknu0kVLbSargoEu1y8LlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});